[package]
name = "scoped_tasks_future"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[dependencies]
crossbeam = "0.2"
futures = "0.1.0"
num_cpus = "1.0"
lazy_static = "0.2"
